config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "questions#index"

  resources :questions do
    resources :answers
  end

  resources :answers do
    member do
      patch 'set_best'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :body, presence: true
  belongs_to :question
  belongs_to :user
  has_many :attachments, as: :attachable, inverse_of: :attachable

  accepts_nested_attributes_for :attachments

  default_scope { order(best_answer: :desc) }

  def set_best!
    question.answers.update_all(best_answer: false)
    update!(best_answer: true)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true

  mount_uploader :file, FileUploader

  validates :file, presence: true

end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, :body, presence:true
  has_many :answers
  has_many :attachments, as: :attachable, inverse_of: :attachable
  belongs_to :user

  accepts_nested_attributes_for :attachments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :questions
  has_many :answers, through: :questions
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_answer, only: [:show, :edit, :update, :destroy, :set_best]

  def index
    @answers = Answer.all
  end

  def new
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    if @answer.save
      flash[:notice] = 'Your answer was successfully added.'
    else
      if @answer.errors.present?
        @answer.errors.full_messages.each do |message|
          flash[:notice] = message + '.\n'
        end
      end
    end
  end

  def update
    @answer = Answer.find(params[:id])
    @question = @answer.question
    if current_user.id == @answer.user_id
      @answer.update(answer_params)
    else
      respond_to do |format|
        format.js { flash.now[:notice] = 'You cannot edit answers you have not created.' }
      end
    end
  end

  def show

  end

  def edit

  end

  def destroy
    if @answer.user_id == current_user.id
      @answer.destroy
    else
      respond_to do |format|
        format.js { flash.now[:notice] = "You can\'\ t delete answers you haven\'\ t created." }
      end
    end
  end

  def set_best
    @question = @answer.question
    if @question.user_id == current_user.id
      @answer.set_best!
    end
  end

  private

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.build
    @answer.attachments.build
  end

  def new
    @question = current_user.questions.new
    @question.attachments.build
  end

  def edit

  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      flash[:notice] = 'Your question was successfully created.'
      redirect_to @question
    else
      if @question.errors.present?
        @question.errors.full_messages.each do |message|
          flash[:notice] = message + '.\n'
        end
      end
      render :new
    end
  end

  def update
    if current_user.id == @question.user_id
      @question.update(question_params)
    else
      respond_to do |format|
        format.js { flash.now[:notice] = 'You cannot edit questions you have not created.' }
      end
    end
  end

  def destroy
    if @question.user_id == current_user.id
      @question.destroy
      flash[:notice] = 'Question was successfully deleted.'
    else
      flash[:notice] = "You can\'\ t delete questions you haven\'\ t created."
    end
    redirect_to questions_path
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer_errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('#answers').html('<%= j render 'questions/given_answer' %>');
  $('#Answer_to_question').val('');
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer_errors').html('<%= j message %>');
  <% end %>
<% else %>
  <% if @answer.destroyed? %>
    $('<%= "#answer_body_#{ @answer.id }" %>').remove();
  <% end %>
<% end %>

$("#flash").html('<%= j render partial: "shared/notice_banner" %>');

app/views/answers/new.html.erb
<%= form_with model: @answer do |form| %>
  <%= form.text_area :body, size: "25x12" %>
  <%= form.button :submit, name: 'question_id', value: params[:question_id] %>
 <% end %>

app/views/answers/set_best.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer_errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('#answers').html('<%= j render 'questions/answers' %>');
<% end %>

$("#flash").html('<%= j render partial: "shared/notice_banner" %>');

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer_errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('#answers').html('<%= j render 'questions/given_answer' %>');
<% end %>

$("#flash").html('<%= j render partial: "shared/notice_banner" %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="flash">
      <%= render partial: "shared/notice_banner" %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/questions/_answers.html.erb
<% if !@question.answers.empty? %>
Answers: <br>
  <% @question.answers.each do |a| %>
   <% if a.persisted? %>
    <div id="answer_body_<%= a.id %>">
      <% if a.best_answer %>
        Best Answer:
      <% end %>
      <%= a.body %>

      <ul>
        <% a.attachments.each do |att| %>
        <li> <%= link_to att.file.identifier, att.file.url %> </li>
        <% end %>
      </ul>

      <% if user_signed_in? %>
        <%= form_for [@question, a], remote: true, html: { id: "edit-answer-#{a.id}" } do |f| %>
          <%= f.label :body, 'edit_answer_body' %>
          <%= f.text_area :body %>
          <%= f.submit 'Save' %>
        <% end %>

        <% if current_user.id == @question.user_id && !a.best_answer %>
          <%= link_to 'Mark as best', set_best_answer_path(a), class: 'mark-best-link', id: "mark-best-link-#{a.id}", method: :patch, remote: true %>
        <% end %>

        <% if current_user.id == a.user_id %>
          <%= link_to 'Edit', '', class: 'edit-answer-link', id: "edit-answer-link-#{a.id}", data: { answer_id: a.id }, remote: true %>
          <%= button_to 'Delete this answer', a, { id: "delete_answer_#{a.id}", method: :delete, remote: true } %>
        <% end %>
      <% end %>
    </div>
   <% end %>
  <% end %>
<% end %>

app/views/questions/_attachment_fields.html.erb
<div class='nested-fields'>
  <div class='field'>
    <%= f.label :file %>
  </div>
  <br>
    <%= f.file_field :file %>
  <%= link_to_remove_association "remove file", f %>
</div>

app/views/questions/_given_answer.html.erb
<p> <%= @answer.body %> </p>
<ul>
  <% @answer.attachments.each do |att| %>
  <li> <%= link_to att.file.identifier, att.file.url %> </li>
  <% end %>
</ul>
<%= link_to 'Edit', '', class: 'edit-answer-link', id: "edit-answer-link-#{@answer.id}", data: { answer_id: @answer.id }, remote: true %>
<%= button_to 'Delete this answer', @answer, { id: "delete_answer_#{@answer.id}", method: :delete } %>

app/views/questions/_question_data.html.erb
<%= @question.title %><br>
<%= @question.body %><br>
Attachments:<br>
<ul>
  <% @question.attachments.each do |att| %>
  <li> <%= link_to att.file.identifier, att.file.url %> </li>
  <% end %>
</ul>

app/views/questions/index.html.erb
<%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
<%= link_to 'Sign in', new_user_session_path %>
<div class="questions_list">
 Questions:
 <br>
 <% if !@questions.empty? %>
  <% @questions.each do |q| %>
      <%= link_to q.title, q %><br>
      answers:
      <%= q.answers.count %> <br>
  <% end %>
<% end %>
</div>
<%= link_to 'Ask question', new_question_path %>

app/views/questions/new.html.erb
<%= form_for @question do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.label :body %>
    <%= form.text_area :body, rows: 8 %>
    <p> Attachments: </p>
    <p>
       <%= form.fields_for :attachments do |att| %>
        <div class='links'>
          <%= link_to_add_association 'add file', form, :attachments, partial: 'attachment_fields' %>
        </div>
      <% end %>
     </p>
    <%= form.submit 'Create' %>
<% end %>

app/views/questions/show.html.erb
<%= link_to 'Back', questions_path %><br>
<% if user_signed_in? %>
  <% if @question.user_id == current_user.id %>
    <p> <%= link_to 'Edit question', '', class: 'edit-question-link', data: { question_id: @question.id }, remote: true %> </p>
    <p> <%= button_to 'Delete question', @question, method: :delete  %> </p>
  <% end %>
<% end %>

<div id='question_data'>
  <%= render 'question_data' %>
    <%= form_for @question, html: { id: "edit-question-#{@question.id}" }, remote: true do |form| %>
      <%= form.label :body, 'edit_question_body' %>
      <%= form.text_area :body %>
      <%= form.submit 'Save' %>
    <% end %>
</div>

<div id='answers'>
 <%= form_for @answer, remote: true do |form| %>
  <%= form.label :body, 'Your answer:' %>
   <div class='answer_errors'>

   </div>
   <%= form.text_area :body, size: "25x12", id: 'Answer_to_question' %>
     <%= form.fields_for :attachments do |att| %>
      <div class='links'>
        <%= link_to_add_association 'add file', form, :attachments, partial: 'attachment_fields' %>
      </div>
     <% end %>
   <% if(!current_user.nil?) %>
    <%= form.hidden_field :user_id, value: current_user.id %>
   <% end %>
    <%= form.button :submit, name: 'question_id', value: @question.id, id:'Send answer' %>
  <% end %>

  <%= render 'answers' %>
</div>

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.question_errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('#question_data').html('<%= j render 'questions/question_data' %>');
<% end %>

$("#flash").html('<%= j render partial: "shared/notice_banner" %>');

app/views/shared/_notice_banner.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>